### ISSUE TITLE
d3-style labels?

### ISSUE THREAD

**Issue by ggoodale** [brucemcpherson/ChordSnip#1]
Hello! Thanks for a great add-on. I'm curious if there's a way to make ChordSnip create d3-style labels for arcs as seen [here](http://mbostock.github.io/d3/talk/20111018/chord.html) instead of putting the label in the arc? My diagram has several arcs that are smaller than the label associated with them, and the labels are doing all sorts of funky things (wrapping weirdly, getting cut off by the outer padding, etc).

**Comment by brucemcpherson** [comment]
The problem is that the real estate available in the sidebar is already small..300px...  and is not expandable.It would be completely taken up with external labels like these, leaves  no room for the chart.
